// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdeJbEZdf0ilfKN7aTLIaetuaC36WqGTw',
    appId: '1:729109950049:web:2594a635334d95a12bc420',
    messagingSenderId: '729109950049',
    projectId: 'wteams-c478f',
    authDomain: 'wteams-c478f.firebaseapp.com',
    storageBucket: 'wteams-c478f.firebasestorage.app',
    measurementId: 'G-L1XMQHXR6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFqyq3jfcPR02GeBA0FoAsEhzByDYJQO0',
    appId: '1:729109950049:android:dae40212c7e1bc202bc420',
    messagingSenderId: '729109950049',
    projectId: 'wteams-c478f',
    storageBucket: 'wteams-c478f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7gqsARGPaxJReLjC1utZTxdyBCXKzN14',
    appId: '1:729109950049:ios:ca55956de95e9cd72bc420',
    messagingSenderId: '729109950049',
    projectId: 'wteams-c478f',
    storageBucket: 'wteams-c478f.firebasestorage.app',
    iosBundleId: 'com.example.wTeams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7gqsARGPaxJReLjC1utZTxdyBCXKzN14',
    appId: '1:729109950049:ios:ca55956de95e9cd72bc420',
    messagingSenderId: '729109950049',
    projectId: 'wteams-c478f',
    storageBucket: 'wteams-c478f.firebasestorage.app',
    iosBundleId: 'com.example.wTeams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdeJbEZdf0ilfKN7aTLIaetuaC36WqGTw',
    appId: '1:729109950049:web:b1374d1b151bc9c62bc420',
    messagingSenderId: '729109950049',
    projectId: 'wteams-c478f',
    authDomain: 'wteams-c478f.firebaseapp.com',
    storageBucket: 'wteams-c478f.firebasestorage.app',
    measurementId: 'G-KFGWZYKNMD',
  );
}
